<?php
/**
 * BrandedFoodObjectDietFlags
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chomp Food Database API Documentation
 *
 * __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API. Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  -----  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  -----  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | |
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * BrandedFoodObjectDietFlags Class Doc Comment
 *
 * @category Class
 * @description An object containing information on an individual ingredient that was flagged as potentially not being compatible with a certain diet
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BrandedFoodObjectDietFlags implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BrandedFoodObject_diet_flags';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ingredient' => 'string',
'ingredient_description' => 'string',
'diet_label' => 'string',
'is_compatible' => 'string',
'compatibility_level' => 'int',
'compatibility_description' => 'string',
'is_allergen' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ingredient' => null,
'ingredient_description' => null,
'diet_label' => null,
'is_compatible' => null,
'compatibility_level' => null,
'compatibility_description' => null,
'is_allergen' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ingredient' => 'ingredient',
'ingredient_description' => 'ingredient_description',
'diet_label' => 'diet_label',
'is_compatible' => 'is_compatible',
'compatibility_level' => 'compatibility_level',
'compatibility_description' => 'compatibility_description',
'is_allergen' => 'is_allergen'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ingredient' => 'setIngredient',
'ingredient_description' => 'setIngredientDescription',
'diet_label' => 'setDietLabel',
'is_compatible' => 'setIsCompatible',
'compatibility_level' => 'setCompatibilityLevel',
'compatibility_description' => 'setCompatibilityDescription',
'is_allergen' => 'setIsAllergen'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ingredient' => 'getIngredient',
'ingredient_description' => 'getIngredientDescription',
'diet_label' => 'getDietLabel',
'is_compatible' => 'getIsCompatible',
'compatibility_level' => 'getCompatibilityLevel',
'compatibility_description' => 'getCompatibilityDescription',
'is_allergen' => 'getIsAllergen'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ingredient'] = isset($data['ingredient']) ? $data['ingredient'] : null;
        $this->container['ingredient_description'] = isset($data['ingredient_description']) ? $data['ingredient_description'] : null;
        $this->container['diet_label'] = isset($data['diet_label']) ? $data['diet_label'] : null;
        $this->container['is_compatible'] = isset($data['is_compatible']) ? $data['is_compatible'] : null;
        $this->container['compatibility_level'] = isset($data['compatibility_level']) ? $data['compatibility_level'] : null;
        $this->container['compatibility_description'] = isset($data['compatibility_description']) ? $data['compatibility_description'] : null;
        $this->container['is_allergen'] = isset($data['is_allergen']) ? $data['is_allergen'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ingredient
     *
     * @return string
     */
    public function getIngredient()
    {
        return $this->container['ingredient'];
    }

    /**
     * Sets ingredient
     *
     * @param string $ingredient Ingredient name
     *
     * @return $this
     */
    public function setIngredient($ingredient)
    {
        $this->container['ingredient'] = $ingredient;

        return $this;
    }

    /**
     * Gets ingredient_description
     *
     * @return string
     */
    public function getIngredientDescription()
    {
        return $this->container['ingredient_description'];
    }

    /**
     * Sets ingredient_description
     *
     * @param string $ingredient_description Description of the ingredient
     *
     * @return $this
     */
    public function setIngredientDescription($ingredient_description)
    {
        $this->container['ingredient_description'] = $ingredient_description;

        return $this;
    }

    /**
     * Gets diet_label
     *
     * @return string
     */
    public function getDietLabel()
    {
        return $this->container['diet_label'];
    }

    /**
     * Sets diet_label
     *
     * @param string $diet_label Name of the diet with which this ingredient may not be compatible
     *
     * @return $this
     */
    public function setDietLabel($diet_label)
    {
        $this->container['diet_label'] = $diet_label;

        return $this;
    }

    /**
     * Gets is_compatible
     *
     * @return string
     */
    public function getIsCompatible()
    {
        return $this->container['is_compatible'];
    }

    /**
     * Sets is_compatible
     *
     * @param string $is_compatible A description of if we believe this ingredient is compatible with the diet
     *
     * @return $this
     */
    public function setIsCompatible($is_compatible)
    {
        $this->container['is_compatible'] = $is_compatible;

        return $this;
    }

    /**
     * Gets compatibility_level
     *
     * @return int
     */
    public function getCompatibilityLevel()
    {
        return $this->container['compatibility_level'];
    }

    /**
     * Sets compatibility_level
     *
     * @param int $compatibility_level A numeric representation of if we believe this ingredient is compatible with the diet. Higher values indicate more compatibility
     *
     * @return $this
     */
    public function setCompatibilityLevel($compatibility_level)
    {
        $this->container['compatibility_level'] = $compatibility_level;

        return $this;
    }

    /**
     * Gets compatibility_description
     *
     * @return string
     */
    public function getCompatibilityDescription()
    {
        return $this->container['compatibility_description'];
    }

    /**
     * Sets compatibility_description
     *
     * @param string $compatibility_description A description of how we graded this ingredient for compatibility with the diet
     *
     * @return $this
     */
    public function setCompatibilityDescription($compatibility_description)
    {
        $this->container['compatibility_description'] = $compatibility_description;

        return $this;
    }

    /**
     * Gets is_allergen
     *
     * @return bool
     */
    public function getIsAllergen()
    {
        return $this->container['is_allergen'];
    }

    /**
     * Sets is_allergen
     *
     * @param bool $is_allergen Boolean representing if the ingredient is a known allergen
     *
     * @return $this
     */
    public function setIsAllergen($is_allergen)
    {
        $this->container['is_allergen'] = $is_allergen;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
