<?php
/**
 * BrandedFoodObjectItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chomp Food Database API Documentation
 *
 * ## Important An **[API key](https://chompthis.com/api/)** is required for access to this API. Get yours at **[https://chompthis.com/api](https://chompthis.com/api/)**.  ### Getting Started   * **[Subscribe](https://chompthis.com/api/#pricing)** to the API.   * Scroll down and click the \"**Authorize**\" button.   * Enter your API key into the \"**value**\" input, click the \"**Authorize**\" button, then click the \"**Close**\" button.   * Scroll down to the section titled \"**default**\" and click on the API endpoint you wish to use.   * Click the \"**Try it out**\" button.   * Enter the information the endpoint requires.   * Click the \"**Execute**\" button.  ### Example    * Branded food response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)**   * Ingredient response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)**  ### How Do I Find My API Key?   * Your API key was sent to the email address you used to create your subscription.   * You will also find your API key in the **[Client Center](https://chompthis.com/api/manage.php)**.   * Read **[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)** for more information.  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | |
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BrandedFoodObjectItemsTest Class Doc Comment
 *
 * @category    Class
 * @description An object containing information for this specific item.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BrandedFoodObjectItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BrandedFoodObjectItems"
     */
    public function testBrandedFoodObjectItems()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "ingredients"
     */
    public function testPropertyIngredients()
    {
    }

    /**
     * Test attribute "package"
     */
    public function testPropertyPackage()
    {
    }

    /**
     * Test attribute "serving"
     */
    public function testPropertyServing()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "nutrients"
     */
    public function testPropertyNutrients()
    {
    }

    /**
     * Test attribute "calorie_conversion_factor"
     */
    public function testPropertyCalorieConversionFactor()
    {
    }

    /**
     * Test attribute "protein_conversion_factor"
     */
    public function testPropertyProteinConversionFactor()
    {
    }

    /**
     * Test attribute "diet_labels"
     */
    public function testPropertyDietLabels()
    {
    }

    /**
     * Test attribute "diet_flags"
     */
    public function testPropertyDietFlags()
    {
    }

    /**
     * Test attribute "packaging_photos"
     */
    public function testPropertyPackagingPhotos()
    {
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
    }

    /**
     * Test attribute "portions"
     */
    public function testPropertyPortions()
    {
    }

    /**
     * Test attribute "allergens"
     */
    public function testPropertyAllergens()
    {
    }

    /**
     * Test attribute "brand_list"
     */
    public function testPropertyBrandList()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "country_details"
     */
    public function testPropertyCountryDetails()
    {
    }

    /**
     * Test attribute "palm_oil_ingredients"
     */
    public function testPropertyPalmOilIngredients()
    {
    }

    /**
     * Test attribute "ingredient_list"
     */
    public function testPropertyIngredientList()
    {
    }

    /**
     * Test attribute "has_english_ingredients"
     */
    public function testPropertyHasEnglishIngredients()
    {
    }

    /**
     * Test attribute "minerals"
     */
    public function testPropertyMinerals()
    {
    }

    /**
     * Test attribute "traces"
     */
    public function testPropertyTraces()
    {
    }

    /**
     * Test attribute "vitamins"
     */
    public function testPropertyVitamins()
    {
    }

    /**
     * Test attribute "common_names"
     */
    public function testPropertyCommonNames()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "footnote"
     */
    public function testPropertyFootnote()
    {
    }
}
